# Llistes


In [116]:
llista=[]# definir una llista buida

In [123]:
llista.append(3)      #afegir 3 a la llista 

In [118]:
llista.clear()        #netejar una llista

In [148]:
llista.remove(5)      #esborrar l'element 5 de la llista

In [124]:
llista2=[1,2,5,8,5,5,8,-9,6] 

In [126]:
llista.extend(llista2) #afegir llista2 al final de la llista1

In [113]:
llista.insert(5,-1000)  #afegir -1000 a la posició 5

In [131]:
llista[3:]       # llista[3:] retorna llista a partir de l'element 3 (inclòs)
llista[:3]       # llista[:3] retorna llista fins l'element 3 (no inclòs)
llista[2:9]      # llista[2:9]  retorna llista des de l'element 2 (inclòs) fins el 9 (no inclòs)

[3, 1, 2, 5, 8, 5, 5, 8, -9, 6]

In [150]:
len(llista)    #retorna longitud de la llista

12

# Arrays

In [1]:
import numpy as np

In [134]:
a=np.array([1,2,5,6,-5]) #definir una numpy array
a

array([ 1,  2,  5,  6, -5])

In [121]:
np.append(a,20) #afegir una dada (20) a la llista a

array([ 1,  2,  5,  6, -5, 20])

In [149]:
np.sort(a) #endreçar llista en ordre ascendent

array([-5,  1,  2,  5,  6])

In [4]:
b=np.linspace(0,9,10) #array des de 0 a 5 amb 10 elements equiespaiats

In [176]:
matriu=b.reshape(5,2) #(files,columes) ha de ser compatible amb la llargada de la array
matriu

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [272]:
np.size(matriu,0) #nombre de files
np.size(matriu,1) #nombre de columnes 

2

In [183]:
matriu[3,1] #seleccionar una entrada d'una matriu [fila,columna]

7.0

In [188]:
c=np.random.randint(1,5,7)   #generar una array de 7 nombres aleatoris de compresos entre 1 i 5 
print(c,c<4)                 #comanda c<4 busca quins elements són més petits que 4

[4 1 1 3 1 1 4] [False  True  True  True  True  True False]


In [235]:
A=np.array([[1,2,3],[-4,5,3],[8,9,-1]])
B=10*np.random.rand(3,3) #generar matriu aleatòria de floats entre 0 i 1
C=np.transpose(B)        #transposar matriu
D=np.linalg.inv(A)       #inversa de la matriu A
np.dot(A,D)              #producte d'arrays ja sigui de matrius, vectors...

array([[ 1.00000000e+00,  1.38777878e-17,  6.93889390e-18],
       [ 0.00000000e+00,  1.00000000e+00, -4.85722573e-17],
       [-1.11022302e-16,  6.93889390e-17,  1.00000000e+00]])

In [264]:
R=np.random.randint(0,5,[5,5]) #matriu de random integers entre 0 i 5 no inclòs
print(R,np.trace(R),np.linalg.det(R))

[[4 0 0 3 3]
 [4 2 4 1 0]
 [0 0 1 1 2]
 [1 0 3 1 4]
 [0 1 2 3 0]] 8 55.000000000000014


In [256]:
v=np.array([5,-3,4])
u=np.array([2,1,-3])
np.dot(v,u)   #producte escalar de v i u
np.cross(v,u) #producte vectorial de v i u


array([ 5, 23, 11])

# útil pel lab

In [153]:
dades=np.array([2,4,2.2,1.3,1.6,1.8])

In [149]:
dades.mean() #mitjana dels valors d'una array

2.15

In [151]:
dades.std()

0.8751190395216717

In [152]:
dades.var()

0.7658333333333333

In [ ]:
dades.min()
dades.max()

In [154]:
novesd=dades.reshape(3,2)
novesd

array([[2. , 4. ],
       [2.2, 1.3],
       [1.6, 1.8]])

In [157]:
np.sum(novesd,axis=0) #axis=0 columna, axis=1 fila

array([5.8, 7.1])

In [160]:
novesd[0,1] #seleccionar una entrada de la matriu [fila,columna]

4.0